services:
  - type: web
    name: slooze-b2b-api
    env: docker
    plan: starter
    autoDeploy: true
    disk:
      name: slooze-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DATA_DIR
        value: /var/data
      - key: ART_DIR
        value: /app/artifacts/eda
    # FastAPI's /docs returns 200 once the server is up
    healthCheckPath: /docs

  - type: cron
    name: slooze-b2b-nightly
    env: docker
    # 02:30 UTC daily (≈ 08:00 IST)
    schedule: "30 2 * * *"
    dockerfilePath: ./cron.Dockerfile
    envVars:
      # Update this after first deploy with your real service URL
      - key: API_URL
        value: https://slooze-b2b-api.onrender.com/run?site=both&pages=2
